import type { Metadata, Viewport } from "next";
import { FC, PropsWithChildren } from "react";
import { roboto } from "@/vendor/fonts";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: ["Next.js", "TypeScript", "News", "Articles", "React", "Explorer"],
  authors: {
    name: "Eligio Elizarraraz Molina",
    url: "https://www.linkedin.com/in/elizarrarazeligio/",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="es">
      <body className={`${roboto.className} antialiased`}>{children}</body>
    </html>
  );
};

export default RootLayout;
